[workspace]
members = [
    "crates/stella_core",
    "crates/stella_frontend",
    "crates/stella_compiler",
    "crates/stella_cli",
    "crates/stella_gpu",
]
default-members = ["crates/stella_cli"]
resolver = "2"

[workspace.package]
version = "0.1.0-alpha.1"
edition = "2024"
authors = ["Seuriin (SSL-ACTX) <seuriin@gmail.com>"]
license = "AGPL-3.0-only"
repository = "https://github.com/SSL-ACTX/stella"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
strip = true
incremental = false

[profile.dev]
opt-level = 0
debug = 1
strip = true
panic = "unwind"
lto = false
codegen-units = 256
incremental = true
